arch:
- aarch64
- amd64
- armv7
- armhf
codenotary: codenotary@degatano.com
description: Loki for Home Assistant (fork)
image: ghcr.io/pdecat/loki/{arch}
init: false
map:
- share
- ssl
name: Loki (fork)
options:
  days_to_keep: 30
  log_level: info
  ssl: false
ports:
  3100/tcp: null
ports_description:
  3100/tcp: HTTP listen port
schema:
  cafile: str?
  certfile: str?
  config_path: str?
  days_to_keep: int(1,)?
  keyfile: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
slug: loki
startup: system
url: https://github.com/pdecat/ha-addon-loki
version: 1.12.0
watchdog: http://[HOST]:3101/ready
